### ISSUE TITLE
Error: Invariant: Method expects to have requestAsyncStorage, none available

### ISSUE THREAD

**Issue by Aaryan6** [supabase-community/vercel-ai-chatbot#14]
# Bug report

## Describe the bug
![image](https://github.com/supabase-community/vercel-ai-chatbot/assets/85422491/ea3b3789-1ced-46e5-a0d7-7dfad587b495)

I got this error after forking the repo and running the command 'npm run dev', I have installed all the packages, and set the values in env.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. npm run dev

## System information

- OS: Windows
- Browser [chrome, edge]
- Version of supabase-js: 2.26.0
- Version of Node.js: v18.16.1

**Comment by dagryl** [comment]
Did you solve the problem?

**Comment by Aaryan6** [comment]
> Did you solve the problem?

Yes I did!, but I forgot to post here

It is caused by this
`export const runtime = 'edge'`

In windows it should be
`export const runtime = 'nodejs'`

Maybe there are 4 files where you need to change this,

but I don't know why 🫤

**Comment by dagryl** [comment]
Upgrading to "next": "14.0.3" solved the problem for me.

**Comment by Aaryan6** [comment]
Do you use Mac or windows?

**Comment by dagryl** [comment]
Windows

**Comment by Aaryan6** [comment]
By changing the runtime from 'edge' to 'nodejs', everything is working!
